# This is a basic workflow to help you get started with Actions

name: checkblock31
on:
  schedule:
    - cron:  "05 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ready to Go
      run: |
        python3 -m pip install -U pip
        mkdir /home/runner/.config/PyFunceble
        pip3 install setuptools
        pip3 install wheel
        pip3 install pyfunceble
        rm -rf deadblock31
        cp PyFunceble.yaml /home/runner/.config/PyFunceble/.PyFunceble.yaml
        python3 checkblock31.py
        rm -rf splitblock31

    - name: push
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Add Deadhost'
        force-add: 'true'
        files: deadblock31
        name: FusionPlmH
        email: leemenhin@gmail.com
        rebase: 'true'
