# This is a basic workflow to help you get started with Actions

name: checkblock1
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Ready to Go
      run: |
        python3 -m pip install -U pip
        pip3 install setuptools
        pip3 install wheel
        pip3 install pyfunceble
        sh check01.sh

    - name: push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Add Deadhost'
        force-add: 'true'
        files: deadblock01
        name: FusionPlmH
        email: leemenhin@gmail.com
        rebase: 'true'
