name: clean
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2  # updated from v2
    - name: Ready to Go
      run: |
        rm -rf splitblock*
        rm -rf deadblock*
        
    - uses: stefanzweifel/git-auto-commit-action@v5.1.0
      with:
           branch: master
           repository: .
           commit_user_name: FusionPlmH
           commit_user_email: leemenhin@gmail.com
           push_options: '--force'
           skip_dirty_check: true
